apiVersion: v1
kind: Service
metadata:
  name: peacepad-backend-service
spec:
  selector:
    app: peacepad-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
